---
- name: Deploy a jar file
  hosts: ubuntu18
  remote_user: server
  tasks:
          - name: Copy jar file to home directory
            copy:
                    src: ./target/DevOpsCalculator-1.0-SNAPSHOT.jar
                    dest: ~/
